version: '3.8'
 
volumes:
  nginx:
  php:
  mysql:
  
services:
  nginx:
    image: jaraim/nginx
    container_name: nginx
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - /root/docker/web/nginx.conf:/etc/nginx/nginx.conf
      - /root/docker/web/certs:/etc/nginx/certs
      - /root/docker/web/html:/var/www/html

  php:
    image: jaraim/php
    container_name: php
    restart: always
    volumes:
      - /root/docker/web/html:/var/www/html

  mysql: 
    image: jaraim/mysql 
    container_name: mysql
    restart: always
    ports:
      - 3306:3306
    volumes: 
      - /root/docker/web/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=webroot
      - MYSQL_DATABASE=web
      - MYSQL_USER=jaraim
      - MYSQL_PASSWORD=jaraimWU
