version: '3.8'
services:
  dockerui:
    image: jaraim/docker-ui
    container_name: dockerui
    restart: unless-stopped
    ports:
      - "8999:8999"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

#默认用户: dockerui
#默认密码: dockerui
