version: '3'
services:
  openresty:
    image: openresty/openresty:1.21.4.3-0-focal
    container_name: openresty
    restart: always
    network_mode: host
    volumes:
      - ./docker/openresty/conf/nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf
      - ./docker/openresty/conf/fastcgi_params:/usr/local/openresty/nginx/conf/fastcgi_params
      - ./docker/openresty/conf/fastcgi-php.conf:/usr/local/openresty/nginx/conf/fastcgi-php.conf
      - ./docker/openresty/log:/var/log/nginx
      - ./docker/openresty/conf/conf.d:/usr/local/openresty/nginx/conf/conf.d/
      - ./docker/openresty/www:/www
      - ./docker/openresty/root:/usr/share/nginx/html
      - ./docker/openresty/etc/localtime:/etc/localtime
    labels:
      createdBy: "Apps"
