version: '3.9'
services:
  rocketchat:
    image: rocket.chat
    container_name: rocketchat
    ports:
      - 8890:3000
    depends_on: 
      - db
    restart: unless-stopped 

    volumes:
      - ./docker/chat/rocketchat/uploads:/app/uploads

    environment: 
      - ROOT_URL=http://localhost
      - MONGO_OPLOG_URL=mongodb://db:27017/rs5 
      - LANGUAGE=zh_CN.UTF-8 

  db:
    image: mongo:latest
    container_name: db
    ports:
      - 27017:27017
    restart: unless-stopped 
    command: --replSet rs5 --oplogSize 256

    volumes:
      - ./docker/chat/mongo/db:/data/db
      - ./docker/chat/mongo/configdb:/data/configdb
volumes:
    rocketchat:
    db:
