#echo "
version: '3.8' 
volumes:
     chatgpt:
services: 
  chatgpt: 
    image: jaraim/chatgpt:latest
    container_name: chatgpt
    restart: unless-stopped   
    ports:
      - 8899:8899
    volumes:
     - ./docker/chatgpt/data:/data
    environment: 
      - PANDORA_CLOUD=cloud  
      - PANDORA_SERVER=0.0.0.0:8899  
      - OPENAI_API_KEY=YOUR_API_KEY  
      - OPENAI_ACCESS_TOKEN=YOUR_ACCESS_TOKEN
#" > compose.yml
