#echo "
services:
  freshrss:
    image: jaraim/freshrss:latest
    container_name: freshrss
    restart: unless-stopped 
    logging:
      options:
        max-size: 10m
    volumes:
      - ./docker/freshrss/data:/var/www/FreshRSS/data
      - ./docker/freshrss/extensions:/var/www/FreshRSS/extensions
    ports:
      - "8081:80"
    environment:
      TZ: Europe/Paris
      CRON_MIN: '2,32'
      FRESHRSS_ENV: development
      LISTEN: 0.0.0.0:80
      TRUSTED_PROXY: 0.0.0.0
      OIDC_ENABLED: 0

volumes:
  freshrss:
#" > compose.yml
