#echo "
version: '3.8'

volumes:
  nginx:

services:
  nginx:
    image: jaraim/nginx:latest
    container_name: nginx
    restart: unless-stopped
    ports:
      - 80:80
      - 81:81
    volumes:
      - ./docker/nginx/data:/data
      - ./docker/nginx/letsencrypt:/etc/letsencrypt
#" > compose.yml
