#echo "
version: '3.8' 
services: 
  nginx:
    image: jaraim/nginx:latest
    container_name:nginx
    restart: always
    ports: 
      - 80:80
      - 81:81  
    # environment: 
    volumes: 
      - /home/nginx/data:/data  
      - /home/nginx/letsencrypt:/etc/letsencrypt 
volumes:
  nginx:      
#" > compose.yml
