#echo "
version: '3.8'
volumes:
  nginx:

services:
  nginx:
    image: jaraim/nginx:latest
    container_name: nginx
    restart: always
    ports:
      - 80:80
      - 81:81
    volumes:
      - /home/nginx/data:/data
      - /home/nginx/letsencrypt:/etc/letsencrypt
#" > compose.yml
