version: '3.8' 
volumes: 
  xui: 
services: 
  xui: 
    image: jaraim/xui:0.3.4.4 
    container_name: xui 
    restart: unless-stopped 
    ports:
      - 2468:54321
    volumes: 
      - ./docker/x-ui/etc/x-ui/:/etc/x-ui/
      - ./docker/x-ui/etc/x-ui/cert/:/etc/x-ui/cert/
      
