version: '3.8' 
volumes: 
  xui: 
services: 
  xui: 
    image: jaraim/xui:0.3.4.4 
    container_name: xui 
    restart: unless-stopped 
    ports:
      - 54321:54321
    volumes: 
      - ./docker/xui:/etc/x-ui/x-ui.db
      - ./docker/xui:/etc/x-ui/cert
