version: '3.9'
volumes:
  xui:
services:
  xui:
    image: jaraim/xui:0.3.4.4
    container_name: xui
    restart: unless-stopped
    ports:
      - 54321:54321
    volumes:
      - ./docker/x-ui/db:/etc/x-ui/
      - ./docker/x-ui/cert/:/root/cert/
