version: "3"
services:
  dujiaoka:
    image: stilleshan/dujiaoka
    container_name: dujiaoka
    environment:
        # - INSTALL=false
        - INSTALL=true
        # - MODIFY=true
    volumes:
      - ./docker/env.conf:/dujiaoka/.env
      - ./docker/uploads:/dujiaoka/public/uploads
      - ./docker/storage:/dujiaoka/storage
    ports:
      - 8090:80         # 8090可以改成任意服务器没有使用过的端口，80不要修改
    restart: always

  dujiaodb:
    image: mariadb:focal
    container_name: dujiaodb
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=changeyourpassword
      - MYSQL_DATABASE=dujiaoka
      - MYSQL_USER=dujiaoka
      - MYSQL_PASSWORD=changeyourpassword
    volumes:
      - ./docker/mysql:/var/lib/mysql

  redis:
    image: redis:alpine
    container_name: redis
    restart: always
    volumes:
      - ./docker/redis:/data
