version: "3"
services:
  dujiaoka:
    image: jiangjuhong/dujiaoka
    container_name: dujiaoka
    ports:
      - 8090:80
    environment:
      - WEB_DOCUMENT_ROOT=/app/public
    restart: unless-stopped
