version: "3"
services:
  dujiaoka:
    image: stilleshan/dujiaoka
    container_name: dujiaoka
    environment:
      - INSTALL=true
    volumes:
      - ./docker/dujiaoka/env.conf:/dujiaoka/.env
      - ./docker/dujiaoka/uploads:/dujiaoka/public/uploads
      - ./docker/dujiaoka/storage:/dujiaoka/storage
    ports:
      - 8090:80
    restart: always

  dujiaodb:
    image: mariadb:focal
    container_name: dujiaodb
    ports:
      - 3309:3306
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=changeyourpassword
      - MYSQL_DATABASE=dujiaoka
      - MYSQL_USER=dujiaoka
      - MYSQL_PASSWORD=changeyourpassword
    volumes:
      - ./docker/dujiaoka/mysql:/var/lib/mysql

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - 6379:6379
    restart: always
    volumes:
      - ./docker/dujiaoka/redis:/data
