#echo "
version: '3.8' 
services: 
  wordpress: 
    image: jaraim/wordpress:latest 
    container_name: wordpress
    restart: unless-stopped  
    ports: 
      - 8080:80  
    depends_on: 
      - mysql
    environment:  
      - WORDPRESS_DB_HOST=mysql  
      - WORDPRESS_DB_USER=exampleuser      
      - WORDPRESS_DB_PASSWORD=examplepass  
      - WORDPRESS_DB_NAME=exampledb        
    volumes: 
      - ./docker/wordpress:/var/wordpress/www/html

  mysql: 
    image: jaraim/mysql 
    container_name: mysql
    restart: unless-stopped  
    ports:
      - 3306:3306
    environment: 
      - MYSQL_DATABASE=exampledb  
      - MYSQL_USER=exampleuser     
      - MYSQL_PASSWORD=examplepass  
      - MYSQL_RANDOM_ROOT_PASSWORD= 1 
    volumes: 
      - ./docker/wordpress/mysql:/var/lib/mysql
volumes: 
  wordpress:
  mysql:
#" > compose.yml
