#echo "
 version: '3.8'
 volumes:
  xui:
 services:
  xui:
    image: jaraim/x-ui
    container_name: xui
    restart: unless-stopped
    network_mode: host
    volumes:
      - ./docker/xui/db:/etc/x-ui/
      - ./docker/xui/cert:/root/cert/
#" > compose.yml
