#cat << EOF > compose.yml
version: '3.8'
volumes:
  onenav:
services:
  onenav:
    image: jaraim/onenav:0.9.32
    container_name: onenav
    restart: unless-stopped 
    ports:
      - 8088:80
    volumes:
      - ./docker/onenav:/data/wwwroot/default/data
#EOF
