#echo "
version: '3.8'
volumes:
  onenav:
services:
  onenav:
    image: jaraim/onenav:0.9.32
    container_name:onenav
    restart: always
    ports:
      - 8088:80
    volumes:
      - /data/onenav:/data/wwwroot/default/data
#" > compose.yml
