#echo "
version: '3.8'

services:
  rsshub:
     image: jaraim/rsshub:latest
     container_name: rsshub
     restart: always
     ports:
      - '1200:1200'
     environment:
      NODE_ENV: production
      CACHE_TYPE: redis
      REDIS_URL: 'redis://redis:6379/'
      PROXY_URI: 'socks5h://warp-socks:9091'
     depends_on:
      - redis
  redis:
     image: jaraim/redis:latest
     container_name: redis
     restart: always
     volumes:
     - redis:/data
  warp-socks:
    image: jaraim/warp-socks:latest
    container_name: warp-socks
    privileged: true
    volumes:
      - /lib/modules:/lib/modules
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
    sysctls:
      net.ipv6.conf.all.disable_ipv6: 0
      net.ipv4.conf.all.src_valid_mark: 1
    healthcheck:
      test: ["CMD", "curl", "-f", "https://www.cloudflare.com/cdn-cgi/trace"]
      interval: 30s
      timeout: 10s
      retries: 5
volumes:
    data:
    rsshub:
    redis:
    warp-socks:
 #" > compose.yml
