cat <<EOF>compose.yml
version: '3.9'
services:
  phpmyadmin:
    image: jaraim/phpmyadmin:5.2.1
    container_name: phpmyadmin
    restart: unless-stopped
    ports:
      - 8089:8089
    volumes:
      - ./docker/phpmyadmin/conf.d/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
  EOF
