#cat << EOF > compose.yml
version: '3'
services:
  cmsdb:
    image: jaraim/mysql:5.7.44
    container_name: cmsdb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: jaraimWU
    networks:
      - 1panel-network
    ports:
      - 3306:3306
    volumes:
      - ./docker/cms/mysql/data/:/var/lib/mysql
      - ./docker/cms/mysql/conf/my.cnf:/etc/mysql/my.cnf
      - ./docker/cms/mysql/log:/var/log/mysql
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    command:
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
      --explicit_defaults_for_timestamp=true
      --lower_case_table_names=1
    labels:
      createdBy: "Apps"
networks:
  1panel-network:
    external: true
#EOF
