#cat << EOF > compose.yml
version: '3'

services:
  mysql:
    image: jaraim/mysql
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: jaraimWU
    networks:
      - 1panel-network
    ports:
      - 3306:3306
    volumes:
      - ./docker/mysql/data/:/var/lib/mysql
      - ./docker/mysql/conf/my.cnf:/etc/mysql/my.cnf
      - ./docker/mysql/log:/var/log/mysql
      - ./docker/mysql/etc/timezone:/etc/timezone:ro
      - ./docker/mysql/etc/localtime:/etc/localtime:ro
    command:
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
      --explicit_defaults_for_timestamp=true
      --lower_case_table_names=1
    labels:
      createdBy: "Apps"
networks:
  1panel-network:
    external: true
#EOF
