version: "3.8"
volumes:
  nextcloud:
services:
  nextcloud:
    image: nextcloud:latest
    container_name: nextcloud
    restart: unless-stopped
    ports:
      - "8686:80"
    volumes:
      - ./docker/nextcloud/config:/var/www/html/config
      - ./docker/nextcloud/data:/var/www/html/data
      - ./docker/nextcloud/apps:/var/www/html/apps
