version: '3'
services:
  www:
    image: tokumeikoi/lcrp
    volumes:
      - './docker/www:/www'
      - './docker/wwwlogs:/wwwlogs'
      - './docker/caddy.conf:/run/caddy/caddy.conf'
      - './docker/supervisord.conf:/run/supervisor/supervisord.conf'
      - './docker/crontabs.conf:/etc/crontabs/root'
      - './docker/.caddy:/root/.caddy'
    ports:
      - '80:80'
      - '443:443'
    restart: always
  mysql:
    image: jaraim/mysql:5.7.44
    volumes:
      - './docker/mysql:/var/lib/mysql'
    restart: always
    environment: 
      MYSQL_ROOT_PASSWORD: v2boardisbest
      MYSQL_DATABASE: v2board
