version: '3.9'
services:
  www:
    image: tokumeikoi/lcrp
    volumes:
      - ./docker/v2board/www/:/www
      - ./docker/v2board/wwwlogs/:/wwwlogs
      - ./docker/v2board/caddy.conf:/run/caddy/caddy.conf
      - ./docker/v2board/supervisord.conf:/run/supervisor/supervisord.conf
      - ./docker/v2board/crontabs.conf:/etc/crontabs/root
      - ./docker/v2board/.caddy:/root/.caddy
    ports:
      - 80:80
      - 443:443
    restart: always
  mysql:
    image: jaraim/mysql:5.7.44
    volumes:
      - ./docker/v2board/mysql:/var/lib/mysql
    restart: always
    environment: 
      MYSQL_ROOT_PASSWORD: jaraim
      MYSQL_DATABASE: v2board
