version: '3.9'
services:
  v2board:
    image: tokumeikoi/lcrp
    container_name: v2board
    ports:
      - 8083:80
    restart: always
    depends_on: 
      - v2boardb
    volumes:
      - ./docker/v2board/www:/www
      - ./docker/v2board/wwwlogs:/wwwlogs
      - ./docker/v2board/caddy.conf:/run/caddy/caddy.conf
      - ./docker/v2board/supervisord.conf:/run/supervisor/supervisord.conf
      - ./docker/v2board/.caddy:/root/.caddy
    environment:  
      - V2BOARD_DB_HOST=v2boardb
      - V2BOARD_DB_USER=exampleuser      
      - V2BOARD_DB_PASSWORD=examplepass  
      - V2BOARD_DB_NAME=exampledb        
    
  v2boardb:
    image: jaraim/mysql:5.7.44
    container_name: v2boardb
    ports:
      -  3308:3306
    restart: always 
    volumes:
      - ./docker/v2board/mysql:/var/lib/mysql
    environment: 
      - MYSQL_DATABASE=exampledb  
      - MYSQL_USER=exampleuser     
      - MYSQL_PASSWORD=examplepass  
      - MYSQL_RANDOM_ROOT_PASSWORD= 1   
